language: java
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  app: young-retreat-81840
  api_key:
    secure: iT2Zmi1+1bZREVgnvBRzE4JtOKcXH6G5Od1GPn1mj6RWwv7RbTUsm53Xkaezup2W/sOM1HoUfUz9Vb4Hf6c5wT3t/W4sobLAVwfB7Pp9K5KwhTLeGx1HQuG9+MdyU4fP5j7C4ZZJmf3qhNBp8rg11RZEl83AxYkYP78ykrk5gR94EgCRKZAEYv6zboJk9rkc3AdIchW5/i/IuSINNogzye+Rim62Fhgow6X6VkEKa7cFPO+US/FksxOXb/CF7ELy/GpqNlfOQunaK24ByCVX/ng97o8oSXwvaEGzm1Kku+914Z0fQK98vAjLJBWTxGwiT/EySZ8z+uERi2OXVUDHpN+tuQVvqsbuuHXDX990Ui/3w0iOxCFEiO1oQ4JoJne+0CRC+PbfVzGztmMvARTckhAzW5fMP42FVwBQ4tfneCQiPBN1we4DdrryrX1o3gZcDpcyBBFkEj8FW+Fgc/sEDr701qjqFonfnwZBdVwtCdqxOxSn0fyHsaRBY/LVcNNHDS9skbT3trTB3dZ3nIhSFkFBhHOVl8h42Om3Y/+K4UT3+uQM/kzyULTdPNyW846cE7kJnb2JVrUJpRhX9805KltWOJHo1zahBmAvXxY87WNJKZhl2oWpePDRaOGLGU6R0X5HDyn+mKt3DZu0l5R76OkTgilqcv4aLRrERC/J5Es=
