language: java
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
- docker
script:
- mvn test
- docker build --tag devopskristiania/pgr301exam .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
- provider: heroku
  app: terraform-heroku-development
  api_key:
    secure: lmR/TrAjxCQjrFY8Nyxek/gOOVGr8s0XVo+JLdhyss4mLzDhwHqHIzrf5p7F7oYVDoykty99NAQ2199AJVt/tMJfaNwmhw1TvxwYn5wj01EurEfLH/r6wgxhwutp2qhh/M2ks14yjpcHTWxmebNIwNBoHmi2Vi7iXzsUtNkUNMHccYjRXSk5JoqB29RnY270m30B6Dc/efChUVJ4bv+bneBgbuNLAs5F6Ebvh+m3D5UsST7bUL0tYP/nmZi0Yfeq5JaoDxZmnvgTVhXcJfXD4lUi2GAzrBsZUSJXi5env5WpIumkrAQPD97cDxUBIo3jcqj5d6edV/CLZYzrdMbNO9oCgPnFT+BrMW4M5pHmN05nlKae0HkwUfRfkSrinPUJxz3X2J/GUaF+w/U/za/P5GyQmEjXlRVJXH1APwDKWEhKMLosXrDNBYujzZD4u4gd2SVvJpmk5ySUX80udmaUmSqdI6QFoJWisr/OG/8aISvZp9yJs3idg83jHSDX/PJSrfnSpOIz3uC3oOTQx+N7LxtFaTzWLjOvQe1MwDadLrkvG+VQ+piDIJhwtUQlL6KMXx+AlexKET81rGjbrCidF8IFhWTM/2izOXCP8dgSuYkRim3NXLgufsFZCzGThAfCBUzC8lKkEbovq/bZcywK1mv+/mzVn/9xiCW4v4WUzSc=
# here we push to image to docker hub
- provider: script
  script: docker push devopskristiania/pgr301exam
  on:
    branch: master
# credentials for dockerhub REG_USER and REG_PASS. here i used travis encrypt to encrypt my second Docker Hub profile created for the exam
env:
  global:
  - secure: Pka6z0de/x8zlwiqyaaNOl3kRvM3FuHQuKii9RGgk7CgA2JQCpBcjEHaInr/HHhduMEX9hQMeRxRZFacoNWu8LUvLzYVYDT7fZ1sJWJnWcJEZyTePEsysS6CKzmftoFULdi9LQOGOF+r9yv98z9zkSKpb+e8uOtzKRIJKr3VxXBbd6F83sFzWmWWCaCfs7usUs4RSooFTJiqeONLuGK+2XHn5eZFrkKo/CozS3lPtYB0yxeuHO6X2SmG2/mlWew3GG3l4pm9mXvqr6/61Yti8+zdwI+4ggEhWPSpLjYFJZSweUE+N4Dics+LScsDzRkfBoTbbH5SOPEmV34/4xk3fFLxaQHaXN9Ajh6m2We81+2cKY6hi/IEkYTmtdGbD2q7bdi0Q9niwPuvaJadnNOOQ+b74oMCHstcJukeTEU/UB2Ga8cO9orVDPofiltpTIDhjAsJU2XG1p77bKqvQv8VsTDrW0a652ptGO2WqQJsRQY+ZnML5V4Zgs8qEjCBEuRCzawlApdejCIpvYJ7fm6DQwQ8C1k9byAjSDWr8nTVPKTl3jzsq723A1GsZRaabMa+7FbfnU8qPbgz1EuARjfiiulGAIrXnKiqtknfU6dPxwelyMEah3WeKvn/uM6HJhW6ppaJavFhYuNyCOlVB3FVsGVyWvb9dP6KxB2+wteOQB4=
  - secure: KADcowp4oWp4MfHY/2CAYPq9udtb+HjTMJRxmBFeQEANmLgcAc2670tBK7dvR4LU9lkJwQYkwXGs3QrW242rTEaft0/rQ4Whx5kXB/C7ErUwdhb91DZiddMlOvX15LUYn8bnYfOvnaW0x+IFEjV+9KBmwHlzaxANdKWSWr/rEnbvWLS7gQUCfIYjnLSveTFqHrx11TJuorS0Jg9iA1TZ8Dn+wNN9exvFsM6zOLQhoQB6bgFkGbm2CdomVwY/Qgz/TKcvvhCPiFRT9qpqzko/NMKcdtAsgyl72D7A0+PIJrWQTlz4PbWERAKHpJKSv/0tvd2+RJjdb8SIL8UiEBDWLJGm6zneNx6OJT/rjj3JaltCdWFu8ulhKPTIZxmkJTfdoSdN937RWcMTFdnD8LpFL44qz3FJeZCD9uFZDG2RaEgQN8Tj169MX7EHanexZGA/+uAw3tkYMcZzN/8yWXroy7PDBy/fsIsK6qf3971TJadzFcoOfAiE1rKH80N5STBJU/PCfp/ySSx2wIqU+wJGPjPHVTD5UxxODJMlCIQKSxdtwfM3gP+Oap5GJpIM1L4lWN15er4Odcp+VJqD8mL3Z4s+g7ItQo7+3vAw8LDYvqYtw12+yMiEAfgX3ybaReIIrGOL1fM03h8MTGXFp0bf1GHTSXm5FBPM7udGD7nPRHs=
