# This image will take openjdk:8-jre-alpine as its base,
FROM openjdk:8-alpine
# VOLUMES are the preferred mechanism for persisting data generated by and used by Docker containers on the host OS
# and share directories from the Host OS with the container.
VOLUME /tmp
# ARG is only available during the build of a Docker image (RUN etc),
# not after the image is created and containers are started from it
# The application's jar file goes here (run mvn clean package -> look at /target)
ARG JAR_FILE=target/PGR301_Applikasjon-0.0.1-SNAPSHOT.jar
# COPY the current directory contents
COPY ${JAR_FILE} PGR301_Applikasjon.jar
# This is where you configure how the application is executed inside the container.
ENTRYPOINT ["java","-jar","PGR301_Applikasjon.jar"]

# det jeg kjørte for å bygge --> docker build -t pgr301_applikasjon .
# run the app with:  docker run -p 8080:8080 pgr301_applikasjon in Docker/Docker-toolbox
# http://192.168.99.102:8080/devices to access page
