spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 #JDBC URL: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    baseline-on-migrate: true

